[package]
name = "wptreport"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zstd = "0.13.2"

[dev-dependencies]
serde-jsonlines = "0.6.0"
xz2 = "0.1.7"
