[package]
name = "wptreport"
version = "0.0.1"
description = "Tools for working with WPT reports"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-jsonlines = "0.6.0"
zstd = "0.13.2"
xz2 = "0.1.7"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"
